{% set data = load_setup_py_data() %}

package:
  name: braceroot
  version: {{ data.get('version') }}

source:
  path: ..


about:
  home: https://github.com/openalea/braceroot
  summary: Modelling BraceRoot contributions to mechanical stability

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: {{PYTHON}} setup.py install 

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
  run:
    - python  >=3.6
    - openalea.plantgl
    - oawidgets
    - scipy

test:
  requires:
    - pytest
  imports:
    - braceroot
  source_files:
    - test/test_*.py
  commands:
   - pytest -v test_*.py
