package:
  name: braceroot
  version: 0.0.1

source:
  path: ..


about:
  home: https://github.com/pradal/braceroot
  summary: BraceRoot contributions to mechanical stability

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - openalea.plantgl

test:
  requires:
    - nose
  imports:
    - braceroot
  source_files:
    - test/test_*.py
  commands:
   - nosetests -v
